services:
  - type: web
    name: arcio-backend
    runtime: node
    rootDir: arcio-backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
